export const polyAtomicIon = [
  { name: "ammonium", formula: "NH4", charge: "1" },
  { name: "hydronium", formula: "H3O", charge: "1" },
  { name: "peroxide", formula: "O2", charge: "2" },
  { name: "hydroxide", formula: "OH", charge: "1" },
  { name: "cyanide", formula: "CN", charge: "1" },

  { name: "azide", formula: "N3", charge: "1" },
  { name: "carbonate", formula: "CO3", charge: "2" },
  { name: "bicarbonate", formula: "HCO3", charge: "1" },
  { name: "nitrate", formula: "NO3", charge: "1" },
  { name: "nitrite", formula: "NO2", charge: "1" },

  { name: "sulfate", formula: "SO4", charge: "2" },
  { name: "hydrogen sulfate", formula: "HSO4", charge: "1" },
  { name: "sulfite", formula: "SO3", charge: "2" },
  { name: "hydrogen sulfite", formula: "HSO3", charge: "1" },
  { name: "phosphate", formula: "PO4", charge: "3" },
  { name: "hydrogen phosphate", formula: "HPO4", charge: "2" },
  { name: "dihydrogen phosphate", formula: "H2PO4", charge: "1" },
  { name: "perchlorate", formula: "ClO4", charge: "1" },
  { name: "chlorate", formula: "ClO3", charge: "1" },
  { name: "chlorite", formula: "ClO2", charge: "1" },

  { name: "hypochlorite", formula: "ClO", charge: "1" },
  { name: "chromate", formula: "CrO4", charge: "2" },
  { name: "dichromate", formula: "Cr2O7", charge: "2" },
  { name: "permanganate", formula: "MnO4", charge: "1" },
  { name: "silicate", formula: "SiO3", charge: "2" },
  { name: "thiosulfite", formula: "S2O3", charge: "2" },
  { name: "thiocyanate", formula: "SCN", charge: "1" },
  { name: "arsenite", formula: "AsO3", charge: "3" },
  { name: "phosphite", formula: "PO3", charge: "3" },
  { name: "acetate", formula: "C2H3O2", charge: "1" },
];
//polyAtomicIon;
export const variableChargeCation = [
  {
    symbol: "Cr",
    charge: [2, 3, 6],
    name: "chromium",
  },
  {
    symbol: "NH4",
    charge: [1],
    name: "ammonium",
  },
  {
    symbol: "Fe",
    charge: [2, 3],
    name: "iron",
  },
  {
    symbol: "Co",
    charge: [2],
    name: "cobalt",
  },
  {
    symbol: "Ni",
    charge: [2],
    name: "nickel",
  },
  {
    symbol: "Cu",
    charge: [1, 2],
    name: "copper",
  },
  {
    symbol: "Ag",
    charge: [1],
    name: "silver",
  },
  {
    symbol: "Au",
    charge: [1, 3],
    name: "gold",
  },
  {
    symbol: "Zn",
    charge: [2],
    name: "zinc",
  },
  {
    symbol: "Hg",
    charge: [2],
    name: "mercury",
  },
  {
    symbol: "Cd",
    charge: [2],
    name: "cadmium",
  },
  {
    symbol: "Mn",
    charge: [2, 3, 4, 6, 7],
    name: "manganese",
  },
  {
    symbol: "V",
    charge: [2, 3, 4, 5],
    name: "vanadium",
  },
  // ------------------------------

  {
    symbol: "Sc",
    charge: [2],
    name: "scandium",
  },
  {
    symbol: "Ti",
    charge: [2, 3, 4],
    name: "Titanium",
  },
  {
    symbol: "Y",
    charge: [3],
    name: "yttrium",
  },
  {
    symbol: "Zr",
    charge: [3, 4],
    name: "zirconium",
  },
  {
    symbol: "Nb",
    charge: [2, 3, 4, 5],
    name: "niobium",
  },
  {
    symbol: "Mo",
    charge: [2, 3, 4, 5, 6],
    name: "molybdenum",
  },
  {
    symbol: "Tc",
    charge: [2, 4, 5],
    name: "technetium",
  },
  {
    symbol: "Ru",
    charge: [2, 3, 4, 5, 6, 7, 8],
    name: "ruthenium",
  },
  {
    symbol: "Rh",
    charge: [2, 3, 4, 6],
    name: "rhodium",
  },
  {
    symbol: "Pd",
    charge: [2, 3, 4],
    name: "palladium",
  },
  {
    symbol: "Cd",
    charge: [2],
    name: "cadmium",
  },
  // ----------------------------------
  {
    symbol: "Pb",
    charge: [2],
    name: "lead",
  },
];

export const elementsArray = [
  {
    name: "hydrogen",
    atomicNum: 1,
    symbol: "H",
    category: "nonmetal",
    atomicMass: "1.0",
    stateStatus: "nonmetal",
    period: 1,
    group: 1,
  },

  {
    name: "helium",
    atomicNum: 2,
    symbol: "He",
    category: "Noble gases",
    atomicMass: "4",
    stateStatus: "nonmetal",
    period: 1,
    group: 0,
  },
  {
    name: "lithium",
    atomicNum: 3,
    symbol: "Li",
    category: "Alkali metals",
    atomicMass: "6.9",
    period: 2,
    group: 1,
  },
  {
    name: "beryllium",
    atomicNum: 4,
    symbol: "Be",
    category: "Alkaline earth metals",
    atomicMass: "9.0",
    period: 2,
    group: 2,
  },
  {
    name: "boron",
    atomicNum: 5,
    symbol: "B",
    category: "Metalloids",
    atomicMass: "10.8",
    period: 2,
    group: 3,
  },
  {
    name: "carbon",
    atomicNum: 6,
    symbol: "C",
    category: "nonmetal",
    atomicMass: "12.0",
    stateStatus: "nonmetal",
    period: 2,
    group: 4,
    ionName: "carbide",
  },
  {
    name: "nitrogen",
    atomicNum: 7,
    symbol: "N",
    category: "nonmetal",
    atomicMass: "14.0",
    stateStatus: "nonmetal",
    period: 2,
    group: 5,
    ionName: "nitride",
  },
  {
    name: "oxygen",
    atomicNum: 8,
    symbol: "O",
    category: "nonmetal",
    atomicMass: "16.0",
    stateStatus: "nonmetal",
    period: 2,
    group: 6,
    ionName: "oxide",
  },
  {
    name: "fluorine",
    atomicNum: 9,
    symbol: "F",
    category: "Halogens",
    atomicMass: "19.0",
    stateStatus: "nonmetal",
    period: 2,
    group: 7,
    ionName: "fluoride",
  },
  {
    name: "neon",
    atomicNum: 10,
    symbol: "Ne",
    category: "Noble gases",
    atomicMass: "20.2",
    stateStatus: "nonmetal",
    period: 2,
    group: 0,
  },
  {
    name: "sodium",
    atomicNum: 11,
    symbol: "Na",
    category: "Alkali metals",
    atomicMass: "23.0",
    period: 3,
    group: 1,
  },
  {
    name: "magnesium",
    atomicNum: 12,
    symbol: "Mg",
    category: "Alkaline earth metals",
    atomicMass: "24.3",
    period: 3,
    group: 2,
  },
  {
    name: "aluminum",
    atomicNum: 13,
    symbol: "Al",
    category: "Post-transition metals",
    atomicMass: "27.0",
    period: 3,
    group: 3,
  },
  {
    name: "silicon",
    atomicNum: 14,
    symbol: "Si",
    category: "Metalloids",
    atomicMass: "28.1",
    period: 3,
    group: 4,
  },
  {
    name: "phosphorus",
    atomicNum: 15,
    symbol: "P",
    category: "nonmetal",
    atomicMass: "31.0",
    stateStatus: "nonmetal",
    period: 3,
    group: 5,
    ionName: "phosphide",
  },
  {
    name: "sulfur",
    atomicNum: 16,
    symbol: "S",
    category: "nonmetal",
    atomicMass: "32.1",
    stateStatus: "nonmetal",
    period: 3,
    group: 6,
    ionName: "sulfide",
  },
  {
    name: "chlorine",
    atomicNum: 17,
    symbol: "Cl",
    category: "Halogens",
    atomicMass: "35.5",
    stateStatus: "nonmetal",
    period: 3,
    group: 7,
    ionName: "chloride",
  },
  {
    name: "argon",
    atomicNum: 18,
    symbol: "Ar",
    category: "Noble gases",
    atomicMass: "39.9",
    stateStatus: "nonmetal",
    period: 3,
    group: 0,
  },
  {
    name: "potassium",
    atomicNum: 19,
    symbol: "K",
    category: "Alkali metals",
    atomicMass: "39.1",
    period: 4,
    group: 1,
  },
  {
    name: "calcium",
    atomicNum: 20,
    symbol: "Ca",
    category: "Alkaline earth metals",
    atomicMass: "40.1",
    period: 4,
    group: 2,
  },
  {
    name: "scandium",
    atomicNum: 21,
    symbol: "Sc",
    category: "Transition metals",
    atomicMass: "45.0",
    period: 4,
    group: "between main groups 2 and 3",
  },
  {
    name: "titanium",
    atomicNum: 22,
    symbol: "Ti",
    category: "Transition metals",
    atomicMass: "47.9",
    period: 4,
    group: "between main groups 2 and 3",
  },

  {
    name: "vanadium",
    atomicNum: 23,
    symbol: "V",
    category: "Transition metals",
    atomicMass: "50.9",
    period: 4,
    group: "between main groups 2 and 3",
  },
  {
    name: "chromium",
    atomicNum: 24,
    symbol: "Cr",
    category: "Transition metals",
    atomicMass: "52.0",
    period: 4,
    group: "between main groups 2 and 3",
  },
  {
    name: "manganese",
    atomicNum: 25,
    symbol: "Mn",
    category: "Transition metals",
    atomicMass: "54.9",
    period: 4,
    group: "between main groups 2 and 3",
  },
  {
    name: "iron",
    atomicNum: 26,
    symbol: "Fe",
    category: "Transition metals",
    atomicMass: "55.9",
    period: 4,
    group: "between main groups 2 and 3",
  },
  {
    name: "cobalt",
    atomicNum: 27,
    symbol: "Co",
    category: "Transition metals",
    atomicMass: "58.9",
    period: 4,
    group: "between main groups 2 and 3",
  },
  {
    name: "nickel",
    atomicNum: 28,
    symbol: "Ni",
    category: "Transition metals",
    atomicMass: "58.7",
    period: 4,
    group: "between main groups 2 and 3",
  },
  {
    name: "copper",
    atomicNum: 29,
    symbol: "Cu",
    category: "Transition metals",
    atomicMass: "63.5",
    period: 4,
    group: "between main groups 2 and 3",
  },
  {
    name: "zinc",
    atomicNum: 30,
    symbol: "Zn",
    category: "Transition metals",
    atomicMass: "65.4",
    period: 4,
    group: "between main groups 2 and 3",
  },
  {
    name: "Gallium",
    atomicNum: 31,
    symbol: "Ga",
    category: "Post-transition metals",
    atomicMass: "69.7",
    period: 4,
    group: 3,
  },
  {
    name: "germanium",
    atomicNum: 32,
    symbol: "Ge",
    category: "Metalloids",
    atomicMass: "72.4",
    period: 4,
    group: 4,
  },
  {
    name: "arsenic",
    atomicNum: 33,
    symbol: "As",
    category: "Metalloids",
    atomicMass: "74.9",
    period: 4,
    group: 5,
    ionName: "arsenide",
  },
  {
    name: "selenium",
    atomicNum: 34,
    symbol: "Se",
    category: "nonmetal",
    atomicMass: "79.0",
    stateStatus: "nonmetal",
    period: 4,
    group: 6,
    ionName: "selenide",
  },
  {
    name: "bromine",
    atomicNum: 35,
    symbol: "Br",
    category: "Halogens",
    atomicMass: "79.9",
    stateStatus: "nonmetal",
    period: 4,
    group: 7,
    ionName: "bromide",
  },
  {
    name: "krypton",
    atomicNum: 36,
    symbol: "Kr",
    category: "Noble gases",
    atomicMass: "83.8",
    stateStatus: "nonmetal",
    period: 4,
    group: 0,
  },
  {
    name: "rubidium",
    atomicNum: 37,
    symbol: "Rb",
    category: "Alkali metals",
    atomicMass: "85.5",
    period: 5,
    group: 1,
  },
  {
    name: "strontium",
    atomicNum: 38,
    symbol: "Sr",
    category: "Alkaline earth metals",
    atomicMass: "87.6",
    period: 5,
    group: 2,
  },
  {
    name: "yitrium",
    atomicNum: 39,
    symbol: "Y",
    category: "Transition metals",
    atomicMass: "88.9",
    period: 5,
    group: "between main groups 2 and 3",
  },
  {
    name: "zirconium",
    atomicNum: 40,
    symbol: "Zr",
    category: "Transition metals",
    atomicMass: "91.2",
    period: 5,
    group: "between main groups 2 and 3",
  },
  {
    name: "niobium",
    atomicNum: 41,
    symbol: "Nb",
    category: "Transition metals",
    atomicMass: "92.9",
    period: 5,
    group: "between main groups 2 and 3",
  },
  {
    name: "molybdenum",
    atomicNum: 42,
    symbol: "Mo",
    category: "Transition metals",
    atomicMass: "95.9",
    period: 5,
    group: "between main groups 2 and 3",
  },
  {
    name: "technetium",
    atomicNum: 43,
    symbol: "Tc",
    category: "Transition metals",
    atomicMass: "99",
    period: 5,
    group: "between main groups 2 and 3",
  },
  {
    name: "ruthenium",
    atomicNum: 44,
    symbol: "Ru",
    category: "Transition metals",
    atomicMass: "101.1",
    period: 5,
    group: "between main groups 2 and 3",
  },

  {
    name: "rhodium",
    atomicNum: 45,
    symbol: "Rh",
    category: "Transition metals",
    atomicMass: "102.9",
    period: 5,
    group: "between main groups 2 and 3",
  },
  {
    name: "palladium",
    atomicNum: 46,
    symbol: "Pd",
    category: "Transition metals",
    atomicMass: "106.4",
    period: 5,
    group: "between main groups 2 and 3",
  },
  {
    name: "silver",
    atomicNum: 47,
    symbol: "Ag",
    category: "Transition metals",
    atomicMass: "107.9",
    period: 5,
    group: "between main groups 2 and 3",
  },
  {
    name: "cadmium",
    atomicNum: 48,
    symbol: "Cd",
    category: "Transition metals",
    atomicMass: "112.4",
    period: 5,
    group: "between main groups 2 and 3",
  },
  {
    name: "indium",
    atomicNum: 49,
    symbol: "In",
    category: "Post-transition metals",
    atomicMass: "114.8",
    period: 5,
    group: 3,
  },
  {
    name: "tin",
    atomicNum: 50,
    symbol: "Sn",
    category: "Post-transition metals",
    atomicMass: "118.7",
    period: 5,
    group: 4,
  },
  {
    name: "antimony",
    atomicNum: 51,
    symbol: "Sb",
    category: "Metalloids",
    atomicMass: "121.8",
    period: 5,
    group: 5,
  },
  {
    name: "tellurium",
    atomicNum: 52,
    symbol: "Te",
    category: "Metalloids",
    atomicMass: "127.6",
    period: 5,
    group: 6,
  },
  {
    name: "iodine",
    atomicNum: 53,
    symbol: "I",
    category: "Halogens",
    atomicMass: "126.9",
    stateStatus: "nonmetal",
    period: 5,
    group: 7,
    ionName: "iodide",
  },
  {
    name: "xenon",
    atomicNum: 54,
    symbol: "Xe",
    category: "Noble gases",
    atomicMass: "131.3",
    stateStatus: "nonmetal",
    period: 5,
    group: 0,
  },
  {
    name: "cesium",
    atomicNum: 55,
    symbol: "Cs",
    category: "Alkali metals",
    atomicMass: "132.9",
    period: 6,
    group: 1,
  },
  {
    name: "barium",
    atomicNum: 56,
    symbol: "Ba",
    category: "Alkaline earth metals",
    atomicMass: "137.4",
    period: 6,
    group: 2,
  },
  {
    name: "lanthanum",
    atomicNum: 57,
    symbol: "La",
    category: "Lanthanides",
    atomicMass: "138.92",
    period: 6,
    group: "between main groups 2 and 3",
  },
  {
    name: "cerium",
    atomicNum: 58,
    symbol: "Ce",
    category: "Lanthanides",
    atomicMass: "140.1",
    period: 6,
    group: "between main groups 2 and 3",
  },
  {
    name: "praseodymium",
    atomicNum: 59,
    symbol: "Pr",
    category: "Lanthanides",
    atomicMass: "140.9",
    period: 6,
    group: "between main groups 2 and 3",
  },
  {
    name: "neodymium",
    atomicNum: 60,
    symbol: "Nd",
    category: "Lanthanides",
    atomicMass: "144.3",
    period: 6,
    group: "between main groups 2 and 3",
  },
  {
    name: "promethium",
    atomicNum: 61,
    symbol: "Pm",
    category: "Lanthanides",
    atomicMass: "145",
    period: 6,
    group: "between main groups 2 and 3",
  },
  {
    name: "samarium",
    atomicNum: 62,
    symbol: "Sm",
    category: "Lanthanides",
    atomicMass: "150.3",
    period: 6,
    group: "between main groups 2 and 3",
  },
  {
    name: "europium",
    atomicNum: 63,
    symbol: "Eu",
    category: "Lanthanides",
    atomicMass: "152",
    period: 6,
    group: "between main groups 2 and 3",
  },
  {
    name: "gadolinium",
    atomicNum: 64,
    symbol: "Gd",
    category: "Lanthanides",
    atomicMass: "157.3",
    period: 6,
    group: "between main groups 2 and 3",
  },
  {
    name: "terbium",
    atomicNum: 65,
    symbol: "Tb",
    category: "Lanthanides",
    atomicMass: "158.9",
    period: 6,
    group: "between main groups 2 and 3",
  },
  {
    name: "dysprosium",
    atomicNum: 66,
    symbol: "Dy",
    category: "Lanthanides",
    atomicMass: "162.5",
    period: 6,
    group: "between main groups 2 and 3",
  },
  {
    name: "holmium",
    atomicNum: 67,
    symbol: "Ho",
    category: "Lanthanides",
    atomicMass: "164.9",
    period: 6,
    group: "between main groups 2 and 3",
  },
  {
    name: "erbium",
    atomicNum: 68,
    symbol: "Er",
    category: "Lanthanides",
    atomicMass: "167.3",
    period: 6,
    group: "between main groups 2 and 3",
  },
  {
    name: "thulium",
    atomicNum: 69,
    symbol: "Tm",
    category: "Lanthanides",
    atomicMass: "168.9",
    period: 6,
    group: "between main groups 2 and 3",
  },
  {
    name: "ytterbium",
    atomicNum: 70,
    symbol: "Yb",
    category: "Lanthanides",
    atomicMass: "173.0",
    period: 6,
    group: "between main groups 2 and 3",
  },
  {
    name: "lutetium",
    atomicNum: 71,
    symbol: "Lu",
    category: "Lanthanides",
    atomicMass: "175",
    period: 6,
    group: "between main groups 2 and 3",
  },
  {
    name: "hafnium",
    atomicNum: 72,
    symbol: "Hf",
    category: "Transition metals",
    atomicMass: "178.5",
    period: 6,
    group: "between main groups 2 and 3",
  },
  {
    name: "tantalium",
    atomicNum: 73,
    symbol: "Ta",
    category: "Transition metals",
    atomicMass: "180.95",
    period: 6,
    group: "between main groups 2 and 3",
  },
  {
    name: "tungsten",
    atomicNum: 74,
    symbol: "W",
    category: "Transition metals",
    atomicMass: "183.9",
    period: 6,
    group: "between main groups 2 and 3",
  },
  {
    name: "rhenium",
    atomicNum: 75,
    symbol: "Re",
    category: "Transition metals",
    atomicMass: "186.22",
    period: 6,
    group: "between main groups 2 and 3",
  },
  {
    name: "osmium",
    atomicNum: 76,
    symbol: "Os",
    category: "Transition metals",
    atomicMass: "190.2",
    period: 6,
    group: "between main groups 2 and 3",
  },
  {
    name: "iridium",
    atomicNum: 77,
    symbol: "Ir",
    category: "Transition metals",
    atomicMass: "192.2",
    period: 6,
    group: "between main groups 2 and 3",
  },
  {
    name: "platinum",
    atomicNum: 78,
    symbol: "Pt",
    category: "Transition metals",
    atomicMass: "195.09",
    period: 6,
    group: "between main groups 2 and 3",
  },
  {
    name: "gold",
    atomicNum: 79,
    symbol: "Au",
    category: "Transition metals",
    atomicMass: "197",
    period: 6,
    group: "between main groups 2 and 3",
  },
  {
    name: "mercury",
    atomicNum: 80,
    symbol: "Hg",
    category: "Transition metals",
    atomicMass: "200.6",
    period: 6,
    group: "between main groups 2 and 3",
  },
  {
    name: "thalium",
    atomicNum: 81,
    symbol: "Tl",
    category: "Post-transition metals",
    atomicMass: "204.4",
    period: 6,
    group: 3,
  },
  {
    name: "lead",
    atomicNum: 82,
    symbol: "Pb",
    category: "Post-transition metals",
    atomicMass: "207.21",
    period: 6,
    group: 4,
  },
  {
    name: "bismuth",
    atomicNum: 83,
    symbol: "Bi",
    category: "Post-transition metals",
    atomicMass: "209",
    period: 6,
    group: 5,
  },
  {
    name: "polonium",
    atomicNum: 84,
    symbol: "Po",
    category: "Metalloids",
    atomicMass: "210",
    period: 6,
    group: 6,
  },
  {
    name: "astatine",
    atomicNum: 85,
    symbol: "At",
    category: "Halogens",
    atomicMass: "210",
    period: 6,
    group: 7,
  },
  {
    name: "radon",
    atomicNum: 86,
    symbol: "Rn",
    category: "Noble gases",
    atomicMass: "222",
    stateStatus: "nonmetal",
    period: 6,
    group: 0,
  },
  {
    name: "francium",
    atomicNum: 87,
    symbol: "Fr",
    category: "Alkali metals",
    atomicMass: "223",
    period: 7,
    group: 1,
  },
  {
    name: "radium",
    atomicNum: 88,
    symbol: "Ra",
    category: "Alkaline earth metals",
    atomicMass: "226.06",
    period: 7,
    group: 2,
  },
  {
    name: "actinium",
    atomicNum: 89,
    symbol: "Ac",
    category: "Actinides",
    atomicMass: "227",
    period: 7,
    group: "between main groups 2 and 3",
  },
  {
    name: "thorium",
    atomicNum: 90,
    symbol: "Th",
    category: "Actinides",
    atomicMass: "232.05",
    period: 7,
    group: "between main groups 2 and 3",
  },
  {
    name: "protactinium",
    atomicNum: 91,
    symbol: "Pa",
    category: "Actinides",
    atomicMass: "231",
    period: 7,
    group: "between main groups 2 and 3",
  },
  {
    name: "uranium",
    atomicNum: 92,
    symbol: "U",
    category: "Actinides",
    atomicMass: "238.07",
    period: 7,
    group: "between main groups 2 and 3",
  },
  {
    name: "neptunium",
    atomicNum: 93,
    symbol: "Np",
    category: "Actinides",
    atomicMass: "237",
    period: 7,
    group: "between main groups 2 and 3",
  },
  {
    name: "plutonium",
    atomicNum: 94,
    symbol: "Pu",
    category: "Actinides",
    atomicMass: "242",
    period: 7,
    group: "between main groups 2 and 3",
  },
  {
    name: "americium",
    atomicNum: 95,
    symbol: "Am",
    category: "Actinides",
    atomicMass: "243",
    period: 7,
    group: "between main groups 2 and 3",
  },
  {
    name: "curium",
    atomicNum: 96,
    symbol: "Cm",
    category: "Actinides",
    atomicMass: "247",
    period: 7,
    group: "between main groups 2 and 3",
  },
  {
    name: "berkelium",
    atomicNum: 97,
    symbol: "Bk",
    category: "Actinides",
    atomicMass: "249",
    period: 7,
    group: "between main groups 2 and 3",
  },
  {
    name: "californium",
    atomicNum: 98,
    symbol: "Cf",
    category: "Actinides",
    atomicMass: "249",
    period: 7,
    group: "between main groups 2 and 3",
  },
  {
    name: "einsteinium",
    atomicNum: 99,
    symbol: "E",
    category: "Actinides",
    atomicMass: "254",
    period: 7,
    group: "between main groups 2 and 3",
  },
  {
    name: "fermium",
    atomicNum: 100,
    symbol: "Fm",
    category: "Actinides",
    atomicMass: "255",
    period: 7,
    group: "between main groups 2 and 3",
  },
  {
    name: "mendelevium",
    atomicNum: 101,
    symbol: "Mv",
    category: "Actinides",
    atomicMass: "256",
    period: 7,
    group: "between main groups 2 and 3",
  },
  {
    name: "nobelium",
    atomicNum: 102,
    symbol: "No",
    category: "Actinides",
    atomicMass: "251",
    period: 7,
    group: "between main groups 2 and 3",
  },
  {
    name: "lawrencium",
    atomicNum: 103,
    symbol: "Lr",
    category: "Actinides",
    atomicMass: "262",
    period: 7,
    group: "between main groups 2 and 3",
  },
  {
    name: "rutherfordium",
    atomicNum: 104,
    symbol: "Rf",
    category: "Transition metals",
    atomicMass: "261",
    period: 7,
    group: "between main groups 2 and 3",
  },
  {
    name: "dubium",
    atomicNum: 105,
    symbol: "Db",
    category: "Transition metals",
    atomicMass: "252",
    period: 7,
    group: "between main groups 2 and 3",
  },
  {
    name: "seaborgium",
    atomicNum: 106,
    symbol: "Sg",
    category: "Transition metals",
    atomicMass: "--",
    period: 7,
    group: "between main groups 2 and 3",
  },
  {
    name: "bohrium",
    atomicNum: 107,
    symbol: "Bh",
    category: "Transition metals",
    atomicMass: "264",
    period: 7,
    group: "between main groups 2 and 3",
  },
  {
    name: "hassium",
    atomicNum: 108,
    symbol: "Hs",
    category: "Transition metals",
    atomicMass: "269",
    period: 7,
    group: "between main groups 2 and 3",
  },
  {
    name: "meitnerium",
    atomicNum: 109,
    symbol: "Mt",
    category: "Unknown properties",
    atomicMass: "278",
    period: 7,
    group: "main groups 2 and 3",
  },
  {
    name: "darnstatium",
    atomicNum: 110,
    symbol: "Ds",
    category: "Unknown properties",
    atomicMass: "281",
    period: 7,
    group: "between main groups 2 and 3",
  },
  {
    name: "roentgenium",
    atomicNum: 111,
    symbol: "Rg",
    category: "Unknown properties",
    atomicMass: "282",
    period: 7,
    group: "between main groups 2 and 3",
  },
  {
    name: "corpernicium",
    atomicNum: 112,
    symbol: "Cn",
    category: "Unknown properties",
    atomicMass: "285",
    period: 7,
    group: "between main groups 2 and 3",
  },
  {
    name: "nihonium",
    atomicNum: 113,
    symbol: "Nh",
    category: "Unknown properties",
    atomicMass: "286",
    period: 7,
    group: 3,
  },
  {
    name: "flerovium",
    atomicNum: 114,
    symbol: "Fl",
    category: "Unknown properties",
    atomicMass: "289",
    period: 7,
    group: 4,
  },
  {
    name: "moscovium",
    atomicNum: 115,
    symbol: "Mc",
    category: "Unknown properties",
    atomicMass: "289",
    period: 7,
    group: 5,
  },
  {
    name: "livermorium",
    atomicNum: 116,
    symbol: "Lv",
    category: "Unknown properties",
    atomicMass: "293",
    period: 7,
    group: 6,
  },
  {
    name: "tennessine",
    atomicNum: 117,
    symbol: "Ts",
    category: "Unknown properties",
    atomicMass: "-",
    period: 7,
    group: 7,
  },
  {
    name: "oganesson",
    atomicNum: 118,
    symbol: "Og",
    category: "Unknown properties",
    atomicMass: "294",
    period: 7,
    group: 0,
  },
];
